services:
  backend:
    build:
      context: .
      dockerfile: ./apps/wishlist/docker/Dockerfile
    volumes:
      - ./keys:/workspace/backend/keys
    environment:
      DB_PASSWORD_FILE: ${POSTGRES_PASSWORD_FILE}

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./keys:/workspace/backend/keys
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PASSWORD_FILE: ${POSTGRES_PASSWORD_FILE}
    networks:
      - app_network